groups:
- last_visited: '2026-05-02T02:07:19.193001'
  url: https://www.facebook.com/groups/2079750999021233/
message_text: Hi, I am looking for an apartment for 1 months, starting May 30 (1 person).
  Is this apartment available? When can I come to see it?
