criteria:
  allows_foreigners: true
  location: null
  max_price: 6.0
  min_price: 0.0
  minimum_lease_months: null
  property_type: null
facebook_groups:
- id: ea07ea22ff6e4de78df9ee728e4f371c
  last_visited: 2026-05-05 21:41:07.357135
  url: https://www.facebook.com/groups/2079750999021233/
message_template: Hi, is this apartment available?
