criteria:
  allows_foreigners: null
  location: null
  max_price: 6.0
  min_price: 0.0
  minimum_lease_months: null
  property_type: null
facebook_groups:
- id: ea07ea22ff6e4de78df9ee728e4f371c
  last_visited: 2026-05-02 22:05:09.429822
  url: https://www.facebook.com/groups/2079750999021233/
message_template: Hi, I am looking for an apartment for 3 months, starting May 12
  (1 person). Is this apartment available? When can I come to see it?
